### ISSUE TITLE
clarify `blockStoreHeight` `appHeight` comparison

### ISSUE THREAD

**Issue by NiloCK** [polymerdao/monomer#10]
from [main.go](https://github.com/polymerdao/monomer/blob/0d4d1852801253cf709ef7bca4d9c8bd2699f86c/cmd/monomer/main.go#L149):

```go
// Ensure appHeight == blockStoreHeight.
   if appHeight == blockStoreHeight+1 {
```

Not obvious to me whether this is a bug or possibly an accommodation between differing systems which start counting at 0 or 1.

**Comment by joshklop** [comment]
There is an edge case in `builder/builder.go` where Monomer crashes after calling `app.Commit` and before calling `blockStore.AddBlock`. In that case, the app will be one block ahead of Monomer.

If this doesn't clarify things, feel free to re-open.
