### ISSUE TITLE
Ensure the docs site builds

### ISSUE THREAD

**Issue by joshklop** [polymerdao/monomer#112]
We use docusaurus. We should ensure that it builds in the CI before merging to `main`.

**Comment by NiloCK** [comment]
Related question:

are we interested in a gh-pages deployment? `http://polymerdao.github.io/monomer` could serve as a temporary destination.

**Comment by joshklop** [comment]
> Related question:
> 
> are we interested in a gh-pages deployment? `http://polymerdao.github.io/monomer` could serve as a temporary destination.

Long-term, yes. I'm hesitant to pull the trigger now just in case we move the repo, which may require redirects and other additional complexity.
