### ISSUE TITLE
Refactor e2e tests

### ISSUE THREAD

**Issue by NiloCK** [polymerdao/monomer#144]
The e2e test has become somewhat unwieldy - lots of setup (stack, clients), triggering operations, and assertions against expected outcomes intermixed. It's easy to lose track of the link between assertions and inputs.

There are also some [timing hacks](https://github.com/polymerdao/monomer/blob/7705f8abfb8fb595d6f2d64f74e6017e83c9d50f/e2e/stack_test.go#L176-L184) present. 

Proposed refactor:
- modify the `stack` constructor / runner to return a richer set of interfacing components (eg, `appchainClient`, `l1RPCClient`)
- Create a structured format, against the above interfaces, with
  - a test name
  - a `triggering event` executing function
  - an `expected outcome` assertion function (the [check for eth minting](https://github.com/polymerdao/monomer/blob/85c2a3c97e9ebc7526d14838c0d6b7aa46869dea/e2e/stack_test.go#L237) in #140 is roughly such an assertion)
- Migrate existing functionality to the structured format

to do:
- ~[ ] remove hardcoded ports from various services~ (nah - more headache than upside)

**Comment by joshklop** [comment]
I really like the first bullet point. We could have the `Stack` do almost all the setup (no need to accept a ton of URLs in the constructor) as long as it returns the proper clients. This is similar to the `System` struct in the `op-e2e` tests I believe.

I'm a little more wary of the second point. This sounds like a lot of callbacks. Perhaps I'm misunderstanding though.

Can we have a PR that implements the first suggestion while we discuss the remaining items?

**Comment by joshklop** [comment]
@NiloCK Instead of having a separate constructor and `Run` method for the `Stack`, maybe we can have a single `Setup(ctx, env, config) (*Stack, error)` where the `Stack` struct contains the clients. Is this what you were thinking?

**Comment by NiloCK** [comment]
> I'm a little more wary of the second point. This sounds like a lot of callbacks. Perhaps I'm misunderstanding though.

I've probably been unclear or misunderstood the implications of my own suggestion, but I despise callbacks and don't usually intend to design toward them.

In this case, think _imperative functions that operate on a stack_, not _stacks that consume imperative functions_.



> @NiloCK Instead of having a separate constructor and `Run` method for the `Stack`, maybe we can have a single `Setup(ctx, env, config) (*Stack, error)` where the `Stack` struct contains the clients. Is this what you were thinking?

Yup.
