### ISSUE TITLE
Add test coverage for eth_getProof

### ISSUE THREAD

**Issue by natebeauregard** [polymerdao/monomer#195]
We have very [minimal test coverage](https://github.com/polymerdao/monomer/blob/4aed3cb/eth/eth_test.go#L134) for `eth_getProof` and don't assert any of the happy path behavior for the [RPC method](https://github.com/polymerdao/monomer/blob/4aed3cbad41dc58c5ec47661021c4b62ec7a629d/eth/get_proof.go#L124). We should add comprehensive test coverage to make sure that all functional cases are covered and that we're accounting for all edge and error cases.

**Comment by AnkushinDaniil** [comment]
I'm working on this

**Comment by natebeauregard** [comment]
Completed in #230
