### ISSUE TITLE
L1 gas computation

### ISSUE THREAD

**Issue by joshklop** [polymerdao/monomer#203]
Ensure we are charging users for the L1 fees associated with their L2 transactions. Otherwise, the batcher will not generate revenue. We need to adapt [this section](https://specs.optimism.io/protocol/exec-engine.html#l1-cost-fees-l1-fee-vault) of the OP Stack specs to work in Monomer.

**Comment by Jesserc** [comment]
I'm working on this

**Comment by natebeauregard** [comment]
Completed in #270
