### ISSUE TITLE
[e2e] `allocs-l1.json does not exist, skipping genesis generation` on e2e test

### ISSUE THREAD

**Issue by NiloCK** [polymerdao/monomer#207]
The following log line appeared on my machine during e2e testing, which I believe is new:

```
file /home/colin/nm/polymerdao/monomer/.devnet/allocs-l1.json does not exist, skipping genesis generation
```

It is also happening on CI:

https://github.com/polymerdao/monomer/actions/runs/10822155982/job/30025536688#step:6:6

The error comes from `optimism.op-e2e.config.init()` - the init function of the `config` package, and it causes an [early exit](https://github.com/ethereum-optimism/optimism/blob/24a8d3e06e61c7a8938dfb7a591345a437036381/op-e2e/config/init.go#L107) from this init. The `init()` seems to make an assumption about the running directory of whatever process invokes it, but this assumption is not true in our e2e test.

It's not clear to me if we ever use the `op-e2e.config` package, but something must, in order to invoke the `init()` function.

**Comment by NiloCK** [comment]
This started occurring on https://github.com/polymerdao/monomer/actions/runs/10798980035, associated with PR https://github.com/polymerdao/monomer/pull/196/files.

*probably* has to do with the introduction of the `e2eutils` package in `op_stack.go`, but this is a bit of a guess.

The error string itself is mildly annoying, but it's a little odd that something is
- initiating the `config` package and relying on it somehow
- doesn't seem to mind that the init exits early


Possible `wontfix` here, just wanted to flag.

**Comment by natebeauregard** [comment]
One potential solution is just moving the `e2e/optimism/.devnet` directory to the monomer root, that may resolve the error message
